

const INIT_ROOMS = 'INIT_ROOMS'
const FETCH_ROOMS_START = 'FETCH_ROOMS_START'
const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS'
const FETCH_ROOMS_ERROR = 'FETCH_ROOMS_ERROR'

const INIT_BOOKINGS = 'INIT_BOOKINGS'
const REGISTER_BOOKING_START = 'REGISTER_BOOKING_START'
const REGISTER_BOOKING_SUCCESS = 'REGISTER_BOOKING_SUCCESS'
const REGISTER_BOOKING_ERROR = 'REGISTER_BOOKING_ERROR'

const CHECK_ROOM_AVAILABILITY_START = 'CHECK_ROOM_AVAILABILITY_START'
const CHECK_ROOM_AVAILABILITY_COMPLETE = 'CHECK_ROOM_AVAILABILITY_COMPLETE'
const ERROR_ON_ROOM_AVAILABILITY_CHECK = 'ERROR_ON_ROOM_AVAILABILITY_CHECK'

export {
    INIT_ROOMS,
    INIT_BOOKINGS,
    FETCH_ROOMS_START,
    FETCH_ROOMS_SUCCESS,
    FETCH_ROOMS_ERROR,
    REGISTER_BOOKING_START,
    REGISTER_BOOKING_SUCCESS,
    REGISTER_BOOKING_ERROR,
    CHECK_ROOM_AVAILABILITY_START,
    CHECK_ROOM_AVAILABILITY_COMPLETE,
    ERROR_ON_ROOM_AVAILABILITY_CHECK
}
